### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by I-Kouta** [I-Kouta/furima-37399#20]
フリマアプリURL
https://furima-37399.herokuapp.com/

Basic認証
ユーザー名: admin
パスワード: 2222

出品者用
アドレス: p@p
パスワード: ppp333

購入者用
アドレス: f@f
パスワード: 111aaa

**Comment by wakazo228** [comment]
@I-Kouta さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### 商品購入機能
- [x] **商品出品時に登録した情報のうち、「商品名・商品画像・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されるようにしましょう**
「配送料の負担」の部分に「発送日の目安」が表示されています。「配送料の負担」が表示されるように修正しましょう。<img width="731" alt="スクリーンショット 2022-02-18 12 08 19" src="https://user-images.githubusercontent.com/53425908/154610427-e3c653fc-7787-471c-a84a-bbe4174a1f7a.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by I-Kouta** [comment]
修正、完了致しました。
URLやBasic認証などの変更はありません。

**Comment by wakazo228** [comment]
@I-Kouta さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！**LGTM**です✨
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

**＜今後の学習例＞**
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

**＜提出物＞**
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

◯最終課題に関する締め切りについての動画
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像3](https://user-images.githubusercontent.com/53425908/154615117-d2176866-2738-486e-a362-7de017f89799.png)
